from . import item_names

#region Park
CubeParkNearSlide = f"{item_names.XPCube} Near Slide"
CubeParkSlide = f"{item_names.XPCube} On Slide"
CubeParkUnderSlide = f"{item_names.XPCube} Under Slide"
CubeParkBouncyMoose = f"{item_names.XPCube} Bouncy Moose"
CubeParkTopHat = f"{item_names.XPCube} Park Top Hat"
CubeParkWater1 = f"{item_names.XPCube} Park Water #1"
CubeParkWater2 = f"{item_names.XPCube} Park Water #2"
CubeParkAcrossWater1 = f"{item_names.XPCube} Park Behind Bomb-able Wall #1"
CubeParkAcrossWater2 = f"{item_names.XPCube} Park Behind Bomb-able Wall #2"
CubeParkAcrossWater3 = f"{item_names.XPCube} Park Across Lake under Bolder"
CubeParkAcrossWater4 = f"{item_names.XPCube} Park Across Lake Boost Pad"
CubeStoneStatue1 = f"{item_names.XPCube} Stone Statue #1"
CubeStoneStatue2 = f"{item_names.XPCube} Stone Statue #2"
CubeStoneStatue3 = f"{item_names.XPCube} Stone Statue #3"
CubeParkFence = f"{item_names.XPCube} Park Fence"
CubeParkLowerSlamPillar = f"{item_names.XPCube} Lower Slam Pillar"
CubeParkUpperSlamPillar = f"{item_names.XPCube} Upper Slam Pillar"
CubeParkAtticDrill1 = f"{item_names.XPCube} Attic Drill #1"
CubeParkAtticDrill2 = f"{item_names.XPCube} Attic Drill #2"
CubeParkAtticHigh1 = f"{item_names.XPCube} Attic Top Ledge #1"
CubeParkAtticHigh2 = f"{item_names.XPCube} Attic Top Ledge #2"
CubeParkAtticHallway = f"{item_names.XPCube} Attic Push Cube Hallway"
CubeParkHouseBookcase = f"{item_names.XPCube} House Bookcase"
CubeParkHouseFoyer1 = f"{item_names.XPCube} House Foyer #1"
CubeParkHouseFoyer2 = f"{item_names.XPCube} House Foyer #2"
CubeParkHouseFoyer3 = f"{item_names.XPCube} House Foyer #3"
CubeParkHouseFoyerTower = f"{item_names.XPCube} House Foyer Tower"
CubeParkTopBouncyMoose = f"{item_names.XPCube} Top Bouncy Moose"
CubeParkTopButtonChallenge1 = f"{item_names.XPCube} Top Boost Ring Challenge #1"
CubeParkTopButtonChallenge2 = f"{item_names.XPCube} Top Boost Ring Challenge #2"
CubeParkTopButtonChallenge3 = f"{item_names.XPCube} Top Boost Ring Challenge #3"
CubeParkDrillPastLake = f"{item_names.XPCube} Behind Bomb-able Wall Underground"
ScrewParkLakeBombYeet = f"{item_names.RedScrew_Short} Lake Bolder"
ScrewParkAtticScrewScrew = f"{item_names.RedScrew_Short} Attic Screw Screw"
ScrewParkAtticDrill = f"{item_names.RedScrew_Short} Attic Drill"
ScrewParkAboveCrank = f"{item_names.RedScrew_Short} Above Crank"
ScrewParkHouseFoyer = f"{item_names.RedScrew_Short} House Foyer"
ScrewParkTopWallJumpChallenge = f"{item_names.RedScrew_Short} Top Wall Jump Challenge"
ChameleonPark = f"{item_names.Moth_Short} Bush"
ChameleonInterior = f"{item_names.Moth_Short} Painting"
CrystalParkAttic = f"{item_names.XPCrystal_Short} Park Attic"
CrystalGarbageGrump = f"{item_names.XPCrystal_Short} Garbage Grump"
MirrorParkSewers = f"{item_names.Mirror_Short} Sewers"
MirrorFoyerLevel3 = f"{item_names.Mirror_Short} Foyer Level 3"
CrankMonsterParkAcrossLake = f"{item_names.Crank} Across Lake"
TrashCanPark = f"{item_names.TrashCan}"
TrashCanAttic1 = f"{item_names.TrashCan} Attic #1"
TrashCanAttic2 = f"{item_names.TrashCan} Attic #2"
TrashCanSewers = f"{item_names.TrashCan} Sewers"
TrashCanFoyer = f"{item_names.TrashCan} Foyer"
TrashCanParkTop = f"{item_names.TrashCan} Park Top"
TrashCanParkTopWallJumpChallenge = f"{item_names.TrashCan} Top Wall Jump Challenge"
TrashCanFoyerLevel3 = f"{item_names.TrashCan} Foyer Level 3"
VoidScrewParkHouse = f"{item_names.VoidScrew} (Park House)"
VoidScrewParkTopHat = f"{item_names.VoidScrew} (Park Top Hat)"
VoidScrewParkOutofBounds = f"{item_names.VoidScrew} (Park Out of Bounds)"
#endregion

#region Hollow
CubeHollowBridge1 = f"{item_names.XPCube} Hollow Bridge #1"
CubeHollowBridge2 = f"{item_names.XPCube} Hollow Bridge #2"
CubeHollowBridge3 = f"{item_names.XPCube} Hollow Bridge #3"
CubeHollowOnTrees = f"{item_names.XPCube} Hollow On Trees"
CubeHollowLeavesUnderOwlTree = f"{item_names.XPCube} Hollow Leaves Under Owl Tree"
CubeHollowLeavesOnOwlTree = f"{item_names.XPCube} Hollow Leaves On Owl Tree"
CubeHollowPillar1 = f"{item_names.XPCube} Hollow Pillar #1"
CubeHollowPillar2 = f"{item_names.XPCube} Hollow Pillar #2"
CubeHollowTrampoline = f"{item_names.XPCube} Hollow Trampoline"
CubeHollowTrinketShop = f"{item_names.XPCube} Hollow Trinket Shop"
CubeHollowClockWallClimb1 = f"{item_names.XPCube} Hollow Clock Wall Climb #1"
CubeHollowClockWallClimb2 = f"{item_names.XPCube} Hollow Clock Wall Climb #2"
CubeHollowPillarOutsideChurch = f"{item_names.XPCube} Hollow Pillar Outside Church"
CubeHollowClockwiseVomit = f"{item_names.XPCube} Hollow Clockwise Vomit"
CubeHollowFartTunnel1 = f"{item_names.XPCube} Hollow Fart Tunnel #1"
CubeHollowFartTunnel2 = f"{item_names.XPCube} Hollow Fart Tunnel #2"
CubeHollowChurch1 = f"{item_names.XPCube} Hollow Pipe"
CubeHollowChurch2 = f"{item_names.XPCube} Hollow Window #1"
CubeHollowChurch3 = f"{item_names.XPCube} Hollow Window #2"
CubeHollowGraveyardPole1 = f"{item_names.XPCube} Hollow Graveyard Pole #1"
CubeHollowGraveyardTacoCat = f"{item_names.XPCube} Hollow Graveyard Tree Branch"
CubeHollowGraveyardPole2 = f"{item_names.XPCube} Hollow Graveyard Pole #2"
CubeHollowGraveyardBehindWetTree = f"{item_names.XPCube} Hollow Graveyard Behind Tree Stump"
CubeHollowGraveyardWater = f"{item_names.XPCube} Hollow Graveyard Water"
CubeHollowGraveyardTombstoneCode1 = f"{item_names.XPCube} Hollow Graveyard Tombstone Code #1 (12311321)"
CubeHollowGraveyardTombstoneCode2 = f"{item_names.XPCube} Hollow Graveyard Tombstone Code #2 (23111323)"
CubeHollowGraveyardTombstoneCode3 = f"{item_names.XPCube} Hollow Graveyard Tombstone Code #3 (21132113)"
CubeHollowBalcony1 = f"{item_names.XPCube} Hollow Balcony #1"
CubeHollowBalcony2 = f"{item_names.XPCube} Hollow Balcony #2"
CubeHollowNearBats1 = f"{item_names.XPCube} Hollow Near Bats #1"
CubeHollowNearBats2 = f"{item_names.XPCube} Hollow Near Bats #2"
CubeHollowDrillRoom1 = f"{item_names.XPCube} Hollow Drill Room #1"
CubeHollowDrillRoom2 = f"{item_names.XPCube} Hollow Drill Room #2"
CubeHollowDrillRoom3 = f"{item_names.XPCube} Hollow Drill Room #3"
CubeHollowDrillUnderRamp = f"{item_names.XPCube} Hollow Drill Under Ramp"
CubeHollowDrillBars1 = f"{item_names.XPCube} Hollow Drill Bars #1"
CubeHollowDrillBars2 = f"{item_names.XPCube} Hollow Drill Bars #2"
CubeHollowDrillUnderChurch1 = f"{item_names.XPCube} Hollow Drill Under Church #1"
CubeHollowDrillUnderChurch2 = f"{item_names.XPCube} Hollow Drill Under Church #2"
CubeHollowDrillDragonMountainside1 = f"{item_names.XPCube} Hollow Drill Dragon Mountainside #1"
CubeHollowDrillDragonMountainside2 = f"{item_names.XPCube} Hollow Drill Dragon Mountainside #2"
CubeHollowHauntedHouseTop1 = f"{item_names.XPCube} Hollow Haunted House Top #1"
CubeHollowHauntedHouseTop2 = f"{item_names.XPCube} Hollow Haunted House Top #2"
CubeHollowHauntedHouseBehindChimney = f"{item_names.XPCube} Hollow Haunted House Behind Chimney"
CubeHollowRavine1 = f"{item_names.XPCube} Hollow Ravine under Climbing Ledge"
CubeHollowRavine2 = f"{item_names.XPCube} Hollow Ravine on Vine"
CubeHollowRavine3 = f"{item_names.XPCube} Hollow Ravine under Vine"
CubeHollowFencedAcrossRavine = f"{item_names.XPCube} Hollow Fenced Across Ravine"
CubeHollowMusicBoxSwim1 = f"{item_names.XPCube} Hollow Music Box Swim #1"
CubeHollowMusicBoxSwim2 = f"{item_names.XPCube} Hollow Music Box Swim #2"
CubeHollowBrickWall1 = f"{item_names.XPCube} Hollow Brick Wall #1"
CubeHollowBrickWall2 = f"{item_names.XPCube} Hollow Brick Wall #2"
CubeHollowBehindSanitaryZoo = f"{item_names.XPCube} Hollow Behind Sanitary Zoo"
CubeHollowSpiderOutsideZoo = f"{item_names.XPCube} Hollow Spider Outside Zoo"
CubeFlippedHollowDragonCrankDrill = f"{item_names.XPCube} Dragon Crank Drill"
CubeFlippedHollowFountainSwim1 = f"{item_names.XPCube} Fountain Swim #1"
CubeFlippedHollowFountainSwim2 = f"{item_names.XPCube} Fountain Swim #2"
CubeFlippedHollowFountainSwim3 = f"{item_names.XPCube} Fountain Swim #3"
CubeFlippedHollowFountainSwim4 = f"{item_names.XPCube} Fountain Swim #4"
CubeHollowTreeFishTimer = f"{item_names.XPCube} Tree Fish Timer"
CubeHollowTreeSwim = f"{item_names.XPCube} Tree Swim"
CubeHollowTreeNearMetalWorm = f"{item_names.XPCube} Tree Near Metal Worm"
CubeHollowGraveyardSpiderCaveDrill = f"{item_names.XPCube} Graveyard Spider Cave Drill"
ScrewHollowTownClock = f"{item_names.RedScrew_Short} (Hollow Town Clock)"
ScrewHollowDrillTowerAlcove = f"{item_names.RedScrew_Short} (Hollow Drill Tower Alcove)"
ScrewHollowBehindHauntedHouse = f"{item_names.RedScrew_Short} (Hollow Behind Haunted House)"
ScrewHollowDragonCave = f"{item_names.RedScrew_Short} (Hollow Dragon Cave)"
ScrewHollowLargeCrankPit = f"{item_names.RedScrew_Short} (Hollow Large Crank Pit)"
ScrewHollowZoo = f"{item_names.RedScrew_Short} (Hollow Zoo)"
ScrewFlippedHollowTreeSideRoom = f"{item_names.RedScrew_Short} (Flipped Hollow Tree Side Room)"
ScrewHollowTreeHighScrew = f"{item_names.RedScrew_Short} (Hollow Tree High Screw)"
ScrewHollowTreeLowScrew = f"{item_names.RedScrew_Short} (Hollow Tree Low Screw)"
ChameleonHollowBush = f"{item_names.Moth_Short} (Hollow Bush)"
ChameleonHollowGraveyard = f"{item_names.Moth_Short} (Hollow Graveyard)"
CrystalHollowTimedFountain = f"{item_names.XPCrystal_Short} (Hollow Timed Fountain)"
CrystalHollowChurchBell = f"{item_names.XPCrystal_Short} (Hollow Church Bell)"
CrystalHollowGraveyardSpiderReward = f"{item_names.XPCrystal_Short} (Hollow Graveyard Spider Reward)"
CrystalHollowDrillPillar = f"{item_names.XPCrystal_Short} (Hollow Drill Pillar)"
CrystalHollowHauntedHouseFreeBird = f"{item_names.XPCrystal_Short} (Hollow Haunted House Free Bird)"
CrystalHollowDragonCave = f"{item_names.XPCrystal_Short} (Hollow Dragon Cave)"
CrystalHollowAboveEntry = f"{item_names.XPCrystal_Short} (Hollow Above Entry)"
CrystalHollowZombieChamber = f"{item_names.XPCrystal_Short} (Hollow Zombie Chamber)"
CrystalHollowFreeStuckPig = f"{item_names.XPCrystal_Short} (Hollow Free Stuck Pig)"
CrystalHollowBombChurchPillar = f"{item_names.XPCrystal_Short} (Hollow Bomb Church Pillar)"
CrystalFlippedHollowCounterclockwiseVomit = f"{item_names.XPCrystal_Short} (Flipped Hollow Counterclockwise Vomit)"
CrystalFlippedHollowGassyMoosey = f"{item_names.XPCrystal_Short} (Flipped Hollow Gassy Moosey)"
MirrorHollowGraveyard = f"{item_names.Mirror_Short} (Hollow Graveyard)"
MirrorHollowZooSideCrank = f"{item_names.Mirror_Short} (Hollow Zoo-Side Crank)"
MirrorFlippedHollowDragonCrank = f"{item_names.Mirror_Short} (Flipped Hollow Dragon Crank)"
MirrorZooMetalWorm = f"{item_names.Mirror_Short} (Zoo Metal Worm)"
CrankHollowHauntedHouseGroundFloor = f"{item_names.Crank} (Hollow Haunted House Ground Floor)"
CrankHollowRavine = f"{item_names.Crank} (Hollow Ravine)"
DiscoBallHollowTrinketShop = f"{item_names.DiscoBall} (Hollow Trinket Shop)"
DiscoBallHollowDragonChest = f"{item_names.DiscoBall} (Hollow Dragon Chest)"
DiscoBallHollowMusicBox = f"{item_names.DiscoBall} (Hollow Music Box)"
DiscoBallHollowZombieChamber = f"{item_names.DiscoBall} (Hollow Zombie Chamber)"
DiscoBallHollowCleanZoo = f"{item_names.DiscoBall} (Hollow Clean Zoo)"
BottleCapHollowGraveyard = f"{item_names.BottleCap} (Hollow Graveyard)"
BottleCapHollowGraveyardInsideWetTree = f"{item_names.BottleCap} (Hollow Graveyard Inside Tree Stump)"
BottleCapHollowRavineClimb = f"{item_names.BottleCap} (Hollow Ravine Climb)"
BottleCapHollowZooRooftop = f"{item_names.BottleCap} (Hollow Zoo Rooftop)"
BottleCapHollowZooSideCrank = f"{item_names.BottleCap} (Hollow Zoo-Side Crank)"
MiracleSoda1 = f"{item_names.MegaDreamSoda} #1"
MiracleSoda2 = f"{item_names.MegaDreamSoda} #2"
VoidScrewHollowOutsideTrinketShop = f"{item_names.VoidScrew} (Hollow Outside Trinket Shop)"
VoidScrewHollowChurch = f"{item_names.VoidScrew} (Hollow Church)"
VoidScrewHollowSky = f"{item_names.VoidScrew} (Hollow Sky)"
VoidScrewTree = f"{item_names.VoidScrew} (Tree)"
VoidScrewKillFish = f"{item_names.VoidScrew} (Kill Fish)"
Drill = f"{item_names.Drill}"
FallWarp = f"{item_names.FallWarp}"
CheeseGrater = f"{item_names.CheeseGrater}"
MetalWorm = "Metal Worm"
DefeatOwlloh = "Defeat Owlloh"
THISGUYWASASICKO = "OH DEAR GOD! THIS GUY WAS A SICKO!!"
HOWDY = "HOWDY"
#endregion
#region Tower
TowerComplete = "Tower Complete"
#endregion
#region Anxiety Tower
CrankAnxietyTower = f"{item_names.Crank} (Anxiety Tower)"
VoidScrewAnxietyTower1 = f"{item_names.VoidScrew} (Anxiety Tower #1)"
VoidScrewAnxietyTower2 = f"{item_names.VoidScrew} (Anxiety Tower #2)"
AnxietyComplete = "Anxiety Tower Complete"
#endregion
#region Some Other Place
VoidScrewSomeOtherPlace = f"{item_names.VoidScrew} (Some Other Place)"
DogGod = "Dog God"
BlueHeadband = "Blue Headband"
GreenHeadband = "Green Headband"
#endregion
#region Achievements
Achievement_LittleCornCadet = "Little Corn Cadet"
Achievement_XPansionPak = "XP-ansion Pak"
Achievement_ImALasagnaHog = "...I'm a Lasagna Hog"
Achievement_CornSyrup = "Corn Syrup"
Achievement_GetNachosOrGetOut = "Get N(achos) or Get Out"
Achievement_Highdive = "Highdive"
Achievement_PrivateScrew = "Private Screw'l"
Achievement_HighBreadHeaven = "High Bread Heaven"
Achievement_SmokingKills = "Smoking Kills"
Achievement_MagicalTetnisChallenge = "Magical Tetnis Challenge"
Achievement_HeroesInAWholeShell = "Heroes in a Whole Shell"
Achievement_AnxietyAttack = "Anxiety Attack"
Achievement_AnnoyedTheVoid = "Annoyed the Void"
Achievement_MaxPower = "maXPower"
Achievement_FeastFitForAKid = "Feast Fit For a Kid"
#endregion
#region Ratsanity
Rat1 = f"{item_names.Rat} Above Fresh Air"
Rat2 = f"{item_names.Rat} Sand Cage"
Rat3 = f"{item_names.Rat} Near Entrance Next To Fence"
Rat4 = f"{item_names.Rat} Wall Cage"
Rat5 = f"{item_names.Rat} In Cage Above Entrance"
Rat6 = f"{item_names.Rat} Grass Area"
#endregion
#region Fishsanity
Fish1 = f"{item_names.Fish} Graveyard Tree Stump"
Fish2 = f"{item_names.Fish} Owl Tree #1"
Fish3 = f"{item_names.Fish} Owl Tree #2"
#endregion

# # world 1
# w1_xp1 = f"{item_names.xp_cube} above Seesaw"  # 113
# w1_xp2 = f"{item_names.xp_cube} behind Slide"  # 116
# w1_xp3 = f"{item_names.xp_cube} on Slide"  # 100
# w1_xp4 = f"{item_names.xp_cube} under Slide"  # 118
# w1_xp5 = f"{item_names.xp_cube} above Top Hat Screw"  # 106
# w1_xp6 = f"{item_names.xp_cube} behind Playground"  # 112
# w1_xp7 = f"{item_names.xp_cube} behind Slam Platform near Lasers"  # 120
# w1_xp8 = f"{item_names.xp_cube} before Lasers"  # 121
# w1_xp9 = f"{item_names.xp_cube} hidden Ledge"  # 129
# w1_xp10 = f"{item_names.xp_cube} top Ledge #1"  # 128, requires drill
# w1_xp11 = f"{item_names.xp_cube} top Ledge #2"  # 130, requires drill
# w1_xp12 = f"{item_names.xp_cube} Cage next to crystal"  # 126, requires drill
# w1_xp13 = f"{item_names.xp_cube} Cage next to dirt"  # 127, requires drill
# w1_xp14 = f"{item_names.xp_cube} in water #1"  # 102
# w1_xp15 = f"{item_names.xp_cube} in water #2"  # 101
# w1_xp16 = f"{item_names.xp_cube} behind bomb-able Wall #1"  # 103
# w1_xp17 = f"{item_names.xp_cube} behind bomb-able Wall #2"  # 104
# w1_xp18 = f"{item_names.xp_cube} underground behind bomb-able Wall"  # 108, requires drill
# w1_xp19 = f"{item_names.xp_cube} in bomb-able Boulder"  # 119
# w1_xp20 = f"{item_names.xp_cube} Booster Wall Jump"  # 105
# w1_xp21 = f"{item_names.xp_cube} from Statue #1"  # 122
# w1_xp22 = f"{item_names.xp_cube} from Statue #2"  # 123
# w1_xp23 = f"{item_names.xp_cube} from Statue #3"  # 124
# w1_xp24 = f"{item_names.xp_cube} behind Shelf"  # 117
# w1_xp25 = f"{item_names.xp_cube} on Ledge above Water"  # 107
# w1_xp26 = f"{item_names.xp_cube} in Cage"  # 115
# w1_xp27 = f"{item_names.xp_cube} on Pipe"  # 114
# w1_xp28 = f"{item_names.xp_cube} in Tree Leaves"  # 131
# w1_xp29 = f"{item_names.xp_cube} above Seesaw"  # 125
# w1_xp30 = f"{item_names.xp_cube} above Booster Rings #1"  # 109
# w1_xp31 = f"{item_names.xp_cube} above Booster Rings #2"  # 110
# w1_xp32 = f"{item_names.xp_cube} above Booster Rings #3"  # 111
# w1_red_screw_1 = f"{item_names.red_screw_short} above Door"  # 134
# w1_red_screw_2 = f"{item_names.red_screw_short} above Screw Wall"  # 137
# w1_red_screw_3 = f"{item_names.red_screw_short} after Dirt"  # 136, requires drill
# w1_red_screw_4 = f"{item_names.red_screw_short} behind bomb-able Wall"  # 138
# w1_red_screw_5 = f"{item_names.red_screw_short} after Wall Jumps"  # 133
# w1_red_screw_6 = f"{item_names.red_screw_short} under bomb-able boulder"  # 135
# w1_moth1 = f"{item_names.moth_short} (Red Boulder)"  # 139
# w1_moth2 = f"{item_names.moth_short} (Picture)"  # 140
# w1_xp_crystal1 = f"{item_names.xp_crystal_short}"  # 143
# w1_xp_crystal2 = f"{item_names.xp_crystal_short} from The Garbage Grump"  # 144
# w1_crank1 = f"{item_names.screw_crank} in chest on Ledge"  # 132
# w1_trash1 = f"{item_names.trash_can} next to Water"  # 152
# w1_trash2 = f"{item_names.trash_can} at The Garbage Grump"  # 148
# w1_trash3 = f"{item_names.trash_can} next to Screw Wall"  # 153
# w1_trash4 = f"{item_names.trash_can} above hidden Staircase"  # 151
# w1_trash5 = f"{item_names.trash_can}"  # 154
# w1_trash6 = f"{item_names.trash_can} next to Cage"  # 155
# w1_trash7 = f"{item_names.trash_can}"  # 150
# w1_trash8 = f"{item_names.trash_can} after Wall Jumps"  # 149
# w1_mirror1 = f"{item_names.mirror_short} in Water Cave"  # 142
# w1_mirror2 = f"{item_names.mirror_short}"  # 141
# w1_void_screw1 = f"{item_names.void_screw} in Mouth Barrel thing"  # 145, requires drill
# w1_void_screw2 = f"{item_names.void_screw} hidden Room above Shelf"  # 146
# w1_void_screw3 = f"{item_names.void_screw} hidden room outside Park"  # 147, requires drill
#
# # world 2
# w2_xp1 = f"{item_names.xp_cube} Bridge #1"  # 254
# w2_xp2 = f"{item_names.xp_cube} Bridge #2"  # 275
# w2_xp3 = f"{item_names.xp_cube} Bridge #3"  # 276
# w2_xp4 = f"{item_names.xp_cube} on Owl Tree Root"  # 226
# w2_xp5 = f"{item_names.xp_cube} under Owl Tree Root"  # 225
# w2_xp6 = f"{item_names.xp_cube} on Pillar #1"  # 216
# w2_xp7 = f"{item_names.xp_cube} on Pillar #2"  # 217
# w2_xp8 = f"{item_names.xp_cube} Dig Cage #1"  # 220 #requires drill
# w2_xp9 = f"{item_names.xp_cube} Dig Cage #2"  # 221 #requires drill
# w2_xp10 = f"{item_names.xp_cube} underground under Music House stairs"  # 248 #requires drill
# w2_xp11 = f"{item_names.xp_cube} above Spring Leaf"  # 266
# w2_xp12 = f"{item_names.xp_cube} Balcony #1"  # 211
# w2_xp13 = f"{item_names.xp_cube} Balcony #2"  # 210
# w2_xp14 = f"{item_names.xp_cube} on Tree above Spring Leaf"  # 209
# w2_xp15 = f"{item_names.xp_cube} underground under Church stairs #1"  # 236 #requires drill
# w2_xp16 = f"{item_names.xp_cube} underground under Church stairs #2"  # 238 #requires drill
# w2_xp17 = f"{item_names.xp_cube} Church pillar"  # 224
# w2_xp18 = f"{item_names.xp_cube} Merry-go-round kid #1"  # 265
# w2_xp19 = f"{item_names.xp_cube} Toxic tunnel #1"  # 215
# w2_xp20 = f"{item_names.xp_cube} Toxic tunnel #2"  # 214
# w2_xp21 = f"{item_names.xp_cube} on Playground wall #1"  # 234
# w2_xp22 = f"{item_names.xp_cube} on Playground wall #2"  # 235
# w2_xp23 = f"{item_names.xp_cube} underground behind Zoo"  # 240 #requires drill
# w2_xp24 = f"{item_names.xp_cube} above Spider near Zoo"  # 252 #requires drill
# w2_xp25 = f"{item_names.xp_cube} above ledge near Clock #1"  # 230
# w2_xp26 = f"{item_names.xp_cube} above ledge near Clock #2"  # 231
# w2_xp27 = f"{item_names.xp_cube} on Tower next to Drill Tower #1"  # 218
# w2_xp28 = f"{item_names.xp_cube} on Tower next to Drill Tower #2"  # 219
# w2_xp29 = f"{item_names.xp_cube} inside Drill Tower #1"  # 242 #requires drill
# w2_xp30 = f"{item_names.xp_cube} inside Drill Tower #2"  # 244 #requires drill
# w2_xp31 = f"{item_names.xp_cube} inside Drill Tower #3"  # 246 #requires drill
# w2_xp32 = f"{item_names.xp_cube} underwater #1"  # 279
# w2_xp33 = f"{item_names.xp_cube} underwater #2"  # 278
# w2_xp34 = f"{item_names.xp_cube} below Ledge"  # 229 #requires drill
# w2_xp35 = f"{item_names.xp_cube} on Vine"  # 227 #requires drill
# w2_xp36 = f"{item_names.xp_cube} below Vine"  # 228 #requires drill
# w2_xp37 = f"{item_names.xp_cube} in bomb-able crate"  # 277 #requires drill
# w2_xp38 = f"{item_names.xp_cube} above Ledge"  # 232 #requires drill
# w2_xp39 = f"{item_names.xp_cube} Right side Pillars"  # 233
# w2_xp40 = f"{item_names.xp_cube} Window #1"  # 255
# w2_xp41 = f"{item_names.xp_cube} Window #2"  # 271
# w2_xp42 = f"{item_names.xp_cube} spikey Pole near Tree Stump"  # 273
# w2_xp43 = f"{item_names.xp_cube} spikey Pole near Church"  # 274
# w2_xp44 = f"{item_names.xp_cube} underwater"  # 256
# w2_xp45 = f"{item_names.xp_cube} on Branch with Bug"  # 261
# w2_xp46 = f"{item_names.xp_cube} on Tree Stump Ledge"  # 253
# w2_xp47 = f"{item_names.xp_cube} Gravestone Puzzle"  # 262
# w2_xp48 = f"{item_names.xp_cube} Dirt Slide below Snake Wall #1"  # 212 #requires drill
# w2_xp49 = f"{item_names.xp_cube} Dirt Slide below Snake Wall #2"  # 213 #requires drill
# w2_xp50 = f"{item_names.xp_cube} on Graveyard Tower #1"  # 222
# w2_xp51 = f"{item_names.xp_cube} on Graveyard Tower #2"  # 223
# w2_xp52 = f"{item_names.xp_cube} next to Chimney"  # 272
# w2_red_screw1 = f"{item_names.red_screw_short} in Zoo"  # 207 #requires drill
# w2_red_screw2 = f"{item_names.red_screw_short} at Owl Pit"  # 201
# w2_red_screw3 = f"{item_names.red_screw_short} behind tower"  # 202
# w2_red_screw4 = f"{item_names.red_screw_short} on Drill Tower"  # 200
# w2_red_screw5 = f"{item_names.red_screw_short} above Clock"  # 203
# w2_moth1 = f"{item_names.moth_short} Bush"  # 297
# w2_moth2 = f"{item_names.moth_short} Gravestone"  # 296
# w2_xp_crystal1 = f"{item_names.xp_crystal_short} Fountain"  # 283
# w2_xp_crystal2 = f"{item_names.xp_crystal_short} on Church Bell"  # 282
# w2_xp_crystal3 = f"{item_names.xp_crystal_short} below dig-through Pillar"  # 286
# w2_xp_crystal4 = f"{item_names.xp_crystal_short} Spider Treasure"  # 291
# w2_xp_crystal5 = f"{item_names.xp_crystal_short}"  # 292
# w2_xp_crystal6 = f"{item_names.xp_crystal_short} from stuck Pig in Owl Pit"  # 294
# w2_xp_crystal7 = f"{item_names.xp_crystal_short} behind painting"  # 285
# w2_bottle_cap1 = f"{item_names.bottle_cap} on Zoo"  # 313 #requires drill
# w2_bottle_cap2 = f"{item_names.bottle_cap} on Gravestone"  # 319
# w2_bottle_cap3 = f"{item_names.bottle_cap} in Tree Stump"  # 317
# w2_bottle_cap4 = f"{item_names.bottle_cap}"  # 311
# w2_bottle_cap5 = f"{item_names.bottle_cap} below Zoo Area"  # 315 #requires drill + screw crank
# w2_mega_soda = f"{item_names.mega_soda}"  # 326 #requires 5 bottle caps
# w2_disco_ball1 = f"{item_names.disco_ball} in Zoo"  # 304 #requires drill
# w2_disco_ball2 = f"{item_names.disco_ball}"  # 300 #requires drill
# w2_disco_ball3 = f"{item_names.disco_ball}"  # 306 #requires drill
# w2_disco_ball4 = f"{item_names.disco_ball}"  # 302 #requires drill + level 3
# w2_disco_ball5 = f"{item_names.disco_ball} in nest"  # 308
# w2_mirror1 = f"{item_names.mirror_short} on Tree Stump"  # 289 #Catch the Cans
# w2_mirror2 = f"{item_names.mirror_short} under Zoo Area"  # 284 #Dig to the Top #requires drill
# w2_crank1 = f"{item_names.screw_crank} in chest"  # 298
# w2_crank2 = f"{item_names.screw_crank}"  # 299
# w2_grater = f"{item_names.grater}"  # 310
# w2_drill = f"{item_names.drill}"  # 1
# w2_fall_warp = f"{item_names.fall_warp}"  # 2
# victory = "Victory"
