Menu = "Menu"
Hub = "Parking Lot"
MonsterPark = "Lexi's Monster Park"
MonsterParkAcrossLake = f"{MonsterPark} Across Lake"  # Either Swim or Slam+Platforming or CanReachParkTop required
MonsterParkHouse = f"{MonsterPark} House"  # (House Crank and Jump and (Wall Jump or Climb) and Headbutt)
MonsterParkHouseFoyer = f"{MonsterPark} House Foyer"  # House and Platforming
MonsterParkAttic = f"{MonsterPark} Attic"  # CanReachAttic
MonsterParkSewers = f"{MonsterPark} Sewers"  # Swim, activated by switches 103
MonsterParkTop = f"{MonsterPark} Top"  # Foyer and Platforming (equal to CanReachParkTop)
WollowsHollow = "Wollow's Hollow"  # Requires CanReachUpperPark and Jump and WallJump, or switch 401 (and whatever to get corn powers)
WollowsHollowChurch = f"{WollowsHollow} Church"  # Switch 212, MaxPlatforming and slam and Hollow
WollowsHollowChurchTop = f"{WollowsHollow} Church Top"  # Church, MaxPlatforming
WollowsHollowGraveyard = f"{WollowsHollow} Graveyard"  # WollowsHollowAboveGraveyard (or, opens via switch 242 as well)
WollowsHollowAboveGraveyard = f"{WollowsHollow} Graveyard from Church"  # Church and MaxPlatforming
WollowsHollowHouse = f"{WollowsHollow} Haunted House Ground Floor"  # Graveyard and Level 2
WollowsHollowHouseTop = f"{WollowsHollow} Haunted House Top Floor"  # DragonPlatforming, Slam
WollowsHollowMusic = f"{WollowsHollow} Music Box"  # Hollow and Level 3
WollowsHollowRavine = f"{WollowsHollow} Ravine"  # Hollow, DrillMinimal
WollowsHollowTrinkets = f"{WollowsHollow} Trinket Shop"  # Hollow
WollowsHollowZombies = f"{WollowsHollow} Zombie Chamber"  # Trinket Shop, MaxPlatforming, Punch
WollowsHollowRooftops = f"{WollowsHollow} Rooftops"  # jump, walljump, climb
WollowsHollowCagedRooftops = f"{WollowsHollow} Caged Rooftop"  # WollowsHollowRooftops and headbutt
WollowsHollowDrillChamber = f"{WollowsHollow} Drill Chamber"  # WollowsHollowCagedRooftops
WollowsHollowZooOutside = f"{WollowsHollow} Outside Zoo"  # Hollow, jump, walljump, headbutt, drill
WollowsHollowZoo = f"{WollowsHollow} Sanitary Zoo"  # ZooOutside, drill down, slam, jump headbutt. Clean zoo trigger is 202
WollowsHollowCave = f"{WollowsHollow} Dragon Cave"  # Graveyard and AllTombstones and Drill and Climb and Jump and WallJump
WollowsHollowTree = f"{WollowsHollow} Tree"
WollowsHollowTreeSideRoom = f"{WollowsHollow} Tree Side Room"  # BatTreeSideRoom
Tower = "Tower"
AnxietyTower = "Anxiety Tower"
SomeOtherPlace = "Some Other Place"  # Hollow, Jump, Headbutt, Climb or WallJump
