from . import LevelNames, RegionNames, ItemNames


#world 1
w1_xp1 = f"{RegionNames.world1}: {ItemNames.xp_cube} above Seesaw" #113
w1_xp2 = f"{RegionNames.world1}: {ItemNames.xp_cube} behind Slide" #116
w1_xp3 = f"{RegionNames.world1}: {ItemNames.xp_cube} on Slide" #100
w1_xp4 = f"{RegionNames.world1}: {ItemNames.xp_cube} under Slide" #118
w1_xp5 = f"{RegionNames.world1}: {ItemNames.xp_cube} above Top Hat Screw" #106
w1_xp6 = f"{RegionNames.world1}: {ItemNames.xp_cube} behind Playground" #112
w1_xp7 = f"{RegionNames.world1}: {ItemNames.xp_cube} behind Slam Platform near Lasers" #120
w1_xp8 = f"{RegionNames.world1}: {ItemNames.xp_cube} before Lasers" #121
w1_xp9 = f"{RegionNames.world1_cube_room}: {ItemNames.xp_cube} hidden Ledge" #129
w1_xp10 = f"{RegionNames.world1_cube_room}: {ItemNames.xp_cube} top Ledge #1" #128, requires drill
w1_xp11 = f"{RegionNames.world1_cube_room}: {ItemNames.xp_cube} top Ledge #2" #130, requires drill
w1_xp12 = f"{RegionNames.world1_cube_room}: {ItemNames.xp_cube} Cage next to crystal" #126, requires drill
w1_xp13 = f"{RegionNames.world1_cube_room}: {ItemNames.xp_cube} Cage next to dirt" #127, requires drill
w1_xp14 = f"{RegionNames.world1}: {ItemNames.xp_cube} in water #1" #102
w1_xp15 = f"{RegionNames.world1}: {ItemNames.xp_cube} in water #2" #101
w1_xp16 = f"{RegionNames.world1}: {ItemNames.xp_cube} behind bomb-able Wall #1" #103
w1_xp17 = f"{RegionNames.world1}: {ItemNames.xp_cube} behind bomb-able Wall #2" #104
w1_xp18 = f"{RegionNames.world1}: {ItemNames.xp_cube} underground behind bomb-able Wall" #108, requires drill
w1_xp19 = f"{RegionNames.world1}: {ItemNames.xp_cube} in bomb-able Boulder" #119
w1_xp20 = f"{RegionNames.world1}: {ItemNames.xp_cube} Booster Wall Jump" #105
w1_xp21 = f"{RegionNames.world1}: {ItemNames.xp_cube} from Statue #1" #122
w1_xp22 = f"{RegionNames.world1}: {ItemNames.xp_cube} from Statue #2" #123
w1_xp23 = f"{RegionNames.world1}: {ItemNames.xp_cube} from Statue #3" #124
w1_xp24 = f"{RegionNames.world1_inside}: {ItemNames.xp_cube} behind Shelf" #117
w1_xp25 = f"{RegionNames.world1_inside}: {ItemNames.xp_cube} on Ledge above Water" #107
w1_xp26 = f"{RegionNames.world1_inside}: {ItemNames.xp_cube} in Cage" #115
w1_xp27 = f"{RegionNames.world1_inside}: {ItemNames.xp_cube} on Pipe" #114
w1_xp28 = f"{RegionNames.world1_inside}: {ItemNames.xp_cube} in Tree Leaves" #131
w1_xp29 = f"{RegionNames.world1_top_area}: {ItemNames.xp_cube} above Seesaw" #125
w1_xp30 = f"{RegionNames.world1_top_area}: {ItemNames.xp_cube} above Booster Rings #1" #109
w1_xp31 = f"{RegionNames.world1_top_area}: {ItemNames.xp_cube} above Booster Rings #2" #110
w1_xp32 = f"{RegionNames.world1_top_area}: {ItemNames.xp_cube} above Booster Rings #3" #111
w1_red_screw_1 = f"{RegionNames.world1}: {ItemNames.red_screw_short} above Door" #134
w1_red_screw_2 = f"{RegionNames.world1_cube_room}: {ItemNames.red_screw_short} above Screw Wall" #137
w1_red_screw_3 = f"{RegionNames.world1_cube_room}: {ItemNames.red_screw_short} after Dirt" #136, requires drill
w1_red_screw_4 = f"{RegionNames.world1_inside}: {ItemNames.red_screw_short} behind bomb-able Wall" #138
w1_red_screw_5 = f"{RegionNames.world1_top_area}: {ItemNames.red_screw_short} after Wall Jumps" #133
w1_red_screw_6 = f"{RegionNames.world1}: {ItemNames.red_screw_short} under bomb-able boulder" #135
w1_moth1 = f"{RegionNames.world1}: {ItemNames.moth_short} (Red Boulder)" #139
w1_moth2 = f"{RegionNames.world1_inside}: {ItemNames.moth_short} (Picture)" #140
w1_xp_crystal1 = f"{RegionNames.world1_cube_room}: {ItemNames.xp_crystal_short}" #143
w1_xp_crystal2 = f"{RegionNames.world1}: {ItemNames.xp_crystal_short} from The Garbage Grump" #144
w1_crank1 = f"{RegionNames.world1}: {ItemNames.screw_crank} in chest on Ledge" #132
w1_trash1 = f"{RegionNames.world1}: {ItemNames.trash_can} next to Water" #152
w1_trash2 = f"{RegionNames.world1}: {ItemNames.trash_can} at The Garbage Grump" #148
w1_trash3 = f"{RegionNames.world1_cube_room}: {ItemNames.trash_can} next to Screw Wall" #153
w1_trash4 = f"{RegionNames.world1_cube_room}: {ItemNames.trash_can} above hidden Staircase" #151
w1_trash5 = f"{RegionNames.world1_inside_level_door}: {ItemNames.trash_can}" #154
w1_trash6 = f"{RegionNames.world1_inside}: {ItemNames.trash_can} next to Cage" #155
w1_trash7 = f"{RegionNames.world1_top_area}: {ItemNames.trash_can}" #150
w1_trash8 = f"{RegionNames.world1_top_area}: {ItemNames.trash_can} after Wall Jumps" #149
w1_mirror1 = f"{RegionNames.world1}: {ItemNames.mirror_short} in Water Cave" #142
w1_mirror2 = f"{RegionNames.world1_inside_level_door}: {ItemNames.mirror_short}" #141
w1_void_screw1 = f"{RegionNames.world1}: {ItemNames.void_screw} in Mouth Barrel thing" #145, requires drill
w1_void_screw2 = f"{RegionNames.world1_inside}: {ItemNames.void_screw} hidden Room above Shelf" #146
w1_void_screw3 = f"{RegionNames.world1}: {ItemNames.void_screw} hidden room outside Park" #147, requires drill

#world 2
w2_xp1 = f"{RegionNames.world2}: {ItemNames.xp_cube} Bridge #1" #254
w2_xp2 = f"{RegionNames.world2}: {ItemNames.xp_cube} Bridge #2" #275
w2_xp3 = f"{RegionNames.world2}: {ItemNames.xp_cube} Bridge #3" #276
w2_xp4 = f"{RegionNames.world2}: {ItemNames.xp_cube} on Owl Tree Root" #226
w2_xp5 = f"{RegionNames.world2}: {ItemNames.xp_cube} under Owl Tree Root" #225
w2_xp6 = f"{RegionNames.world2}: {ItemNames.xp_cube} on Pillar #1" #216
w2_xp7 = f"{RegionNames.world2}: {ItemNames.xp_cube} on Pillar #2" #217
w2_xp8 = f"{RegionNames.world2}: {ItemNames.xp_cube} Dig Cage #1" #220 #requires drill
w2_xp9 = f"{RegionNames.world2}: {ItemNames.xp_cube} Dig Cage #2" #221 #requires drill
w2_xp10 = f"{RegionNames.world2}: {ItemNames.xp_cube} underground under Music House stairs" #248 #requires drill
w2_xp11 = f"{RegionNames.world2}: {ItemNames.xp_cube} above Spring Leaf" #266
w2_xp12 = f"{RegionNames.world2}: {ItemNames.xp_cube} Balcony #1" #211
w2_xp13 = f"{RegionNames.world2}: {ItemNames.xp_cube} Balcony #2" #210
w2_xp14 = f"{RegionNames.world2}: {ItemNames.xp_cube} on Tree above Spring Leaf" #209
w2_xp15 = f"{RegionNames.world2}: {ItemNames.xp_cube} underground under Church stairs #1" #236 #requires drill
w2_xp16 = f"{RegionNames.world2}: {ItemNames.xp_cube} underground under Church stairs #2" #238 #requires drill
w2_xp17 = f"{RegionNames.world2}: {ItemNames.xp_cube} Church pillar" #224
w2_xp18 = f"{RegionNames.world2}: {ItemNames.xp_cube} Merry-go-round kid #1" #265
w2_xp19 = f"{RegionNames.world2}: {ItemNames.xp_cube} Toxic tunnel #1" #215
w2_xp20 = f"{RegionNames.world2}: {ItemNames.xp_cube} Toxic tunnel #2" #214
w2_xp21 = f"{RegionNames.world2}: {ItemNames.xp_cube} on Playground wall #1" #234
w2_xp22 = f"{RegionNames.world2}: {ItemNames.xp_cube} on Playground wall #2" #235
w2_xp23 = f"{RegionNames.world2}: {ItemNames.xp_cube} underground behind Zoo" #240 #requires drill
w2_xp24 = f"{RegionNames.world2}: {ItemNames.xp_cube} above Spider near Zoo" #252 #requires drill
w2_xp25 = f"{RegionNames.world2}: {ItemNames.xp_cube} above ledge near Clock #1" #230
w2_xp26 = f"{RegionNames.world2}: {ItemNames.xp_cube} above ledge near Clock #2" #231
w2_xp27 = f"{RegionNames.world2}: {ItemNames.xp_cube} on Tower next to Drill Tower #1" #218
w2_xp28 = f"{RegionNames.world2}: {ItemNames.xp_cube} on Tower next to Drill Tower #2" #219
w2_xp29 = f"{RegionNames.world2}: {ItemNames.xp_cube} inside Drill Tower #1" #242 #requires drill
w2_xp30 = f"{RegionNames.world2}: {ItemNames.xp_cube} inside Drill Tower #2" #244 #requires drill
w2_xp31 = f"{RegionNames.world2}: {ItemNames.xp_cube} inside Drill Tower #3" #246 #requires drill
w2_xp32 = f"{RegionNames.world2_music_house}: {ItemNames.xp_cube} underwater #1" #279
w2_xp33 = f"{RegionNames.world2_music_house}: {ItemNames.xp_cube} underwater #2" #278
w2_xp34 = f"{RegionNames.world2_chasm}: {ItemNames.xp_cube} below Ledge" #229 #requires drill
w2_xp35 = f"{RegionNames.world2_chasm}: {ItemNames.xp_cube} on Vine" #227 #requires drill
w2_xp36 = f"{RegionNames.world2_chasm}: {ItemNames.xp_cube} below Vine" #228 #requires drill
w2_xp37 = f"{RegionNames.world2_chasm}: {ItemNames.xp_cube} in bomb-able crate" #277 #requires drill
w2_xp38 = f"{RegionNames.world2_shop_upper}: {ItemNames.xp_cube} above Ledge" #232 #requires drill
w2_xp39 = f"{RegionNames.world2_church}: {ItemNames.xp_cube} Right side Pillars" #233
w2_xp40 = f"{RegionNames.world2_church}: {ItemNames.xp_cube} Window #1" #255
w2_xp41 = f"{RegionNames.world2_church}: {ItemNames.xp_cube} Window #2" #271
w2_xp42 = f"{RegionNames.world2_graveyard}: {ItemNames.xp_cube} spikey Pole near Tree Stump" #273
w2_xp43 = f"{RegionNames.world2_graveyard}: {ItemNames.xp_cube} spikey Pole near Church" #274
w2_xp44 = f"{RegionNames.world2_graveyard}: {ItemNames.xp_cube} underwater" #256
w2_xp45 = f"{RegionNames.world2_graveyard}: {ItemNames.xp_cube} on Branch with Bug" #261
w2_xp46 = f"{RegionNames.world2_graveyard}: {ItemNames.xp_cube} on Tree Stump Ledge" #253
w2_xp47 = f"{RegionNames.world2_graveyard}: {ItemNames.xp_cube} Gravestone Puzzle" #262
w2_xp48 = f"{RegionNames.world2_graveyard}: {ItemNames.xp_cube} Dirt Slide below Snake Wall #1" #212 #requires drill
w2_xp49 = f"{RegionNames.world2_graveyard}: {ItemNames.xp_cube} Dirt Slide below Snake Wall #2" #213 #requires drill
w2_xp50 = f"{RegionNames.world2_snake_wall}: {ItemNames.xp_cube} on Graveyard Tower #1" #222
w2_xp51 = f"{RegionNames.world2_snake_wall}: {ItemNames.xp_cube} on Graveyard Tower #2" #223
w2_xp52 = f"{RegionNames.world2_graveyard_tower_top}: {ItemNames.xp_cube} next to Chimney" #272
w2_red_screw1 = f"{RegionNames.world2_zoo}: {ItemNames.red_screw_short} in Zoo" #207 #requires drill
w2_red_screw2 = f"{RegionNames.world2}: {ItemNames.red_screw_short} at Owl Pit" #201
w2_red_screw3 = f"{RegionNames.world2_graveyard}: {ItemNames.red_screw_short} behind tower" #202
w2_red_screw4 = f"{RegionNames.world2}: {ItemNames.red_screw_short} on Drill Tower" #200
w2_red_screw5 = f"{RegionNames.world2}: {ItemNames.red_screw_short} above Clock" #203
w2_moth1 = f"{RegionNames.world2}: {ItemNames.moth_short} Bush" #297
w2_moth2 = f"{RegionNames.world2_graveyard}: {ItemNames.moth_short} Gravestone" #296
w2_xp_crystal1 = f"{RegionNames.world2}: {ItemNames.xp_crystal_short} Fountain" #283
w2_xp_crystal2 = f"{RegionNames.world2}: {ItemNames.xp_crystal_short} on Church Bell" #282
w2_xp_crystal3 = f"{RegionNames.world2}: {ItemNames.xp_crystal_short} below dig-through Pillar" #286
w2_xp_crystal4 = f"{RegionNames.world2}: {ItemNames.xp_crystal_short} Spider Treasure" #291
w2_xp_crystal5 = f"{RegionNames.world2_coffin}: {ItemNames.xp_crystal_short}" #292
w2_xp_crystal6 = f"{RegionNames.world2}: {ItemNames.xp_crystal_short} from stuck Pig in Owl Pit" #294
w2_xp_crystal7 = f"{RegionNames.world2_graveyard}: {ItemNames.xp_crystal_short} behind painting" #285
w2_bottle_cap1 = f"{RegionNames.world2}: {ItemNames.bottle_cap} on Zoo" #313 #requires drill
w2_bottle_cap2 = f"{RegionNames.world2_graveyard}: {ItemNames.bottle_cap} on Gravestone" #319
w2_bottle_cap3 = f"{RegionNames.world2_graveyard}: {ItemNames.bottle_cap} in Tree Stump" #317
w2_bottle_cap4 = f"{RegionNames.world2_chasm}: {ItemNames.bottle_cap}" #311
w2_bottle_cap5 = f"{RegionNames.world2}: {ItemNames.bottle_cap} below Zoo Area" #315 #requires drill + screw crank
w2_mega_soda = f"{RegionNames.world2}: {ItemNames.mega_soda}" #326 #requires 5 bottle caps
w2_disco_ball1 = f"{RegionNames.world2_zoo}: {ItemNames.disco_ball} in Zoo" #304 #requires drill
w2_disco_ball2 = f"{RegionNames.world2_snake_wall}: {ItemNames.disco_ball}" #300 #requires drill
w2_disco_ball3 = f"{RegionNames.world2_shop_upper}: {ItemNames.disco_ball}" #306 #requires drill
w2_disco_ball4 = f"{RegionNames.world2_coffin}: {ItemNames.disco_ball}" #302 #requires drill + level 3
w2_disco_ball5 = f"{RegionNames.world2_music_house}: {ItemNames.disco_ball} in nest" #308
w2_mirror1 = f"{RegionNames.world2_graveyard}: {ItemNames.mirror_short} on Tree Stump" #289 #Catch the Cans
w2_mirror2 = f"{RegionNames.world2}: {ItemNames.mirror_short} under Zoo Area" #284 #Dig to the Top #requires drill
w2_crank1 = f"{RegionNames.world2_graveyard_tower}: {ItemNames.screw_crank} in chest" #298
w2_crank2 = f"{RegionNames.world2_chasm}: {ItemNames.screw_crank}" #299
w2_grater = f"{RegionNames.world2_graveyard}: {ItemNames.grater}" #310
w2_drill = f"{RegionNames.world2}: {ItemNames.drill}" #1
w2_fall_warp = f"{RegionNames.world2_church}: {ItemNames.fall_warp}" #2

victory = "Victory"

